[package]
name = "aoc-2020-06"
version = "0.1.0"
authors = ["MÃ¥rten Kongstad <marten.kongstad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
